name: CI/CD Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear dependencies cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Building project
        run: npm run build
